# Generated by Django 2.2.7 on 2019-11-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.CharField(default='aaa', max_length=200, verbose_name='投稿者'),
        ),
    ]
