# Generated by Django 2.2.7 on 2019-11-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_item_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='投稿者'),
        ),
    ]
