# Generated by Django 2.2.7 on 2019-11-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191112_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='link',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='備考'),
        ),
    ]
