# Generated by Django 2.2.7 on 2019-11-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_item_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='URL'),
        ),
    ]
