# Generated by Django 2.2.7 on 2019-11-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191119_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200, verbose_name='タイトル'),
        ),
    ]
