# Generated by Django 2.2.7 on 2019-11-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191119_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='age',
        ),
        migrations.AddField(
            model_name='item',
            name='cat',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='商品名'),
        ),
    ]
