# Generated by Django 2.2.7 on 2019-12-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191120_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.TextField(max_length=600, verbose_name='URL'),
        ),
    ]
